### ISSUE TITLE
Add Rocket.Chat Android app on the F-Droid FOSS catalogue

### ISSUE THREAD

**Issue by ghost** [RocketChat/Rocket.Chat.Cordova#104]
Hello,

Since Rocket.Chat and the Rocket.Chat app are Free and Open Source Softwares could you consider putting the Android app on [F-Droid](https://f-droid.org/), a catalog for FOSS applications on Android. It would allow those who do not wish to not use (or as little as possible) the services from Google (here the Play Store) to easily have access to the Rocket.Chat Android app.

Since the app is under the MIT license there shouldn't be any problem but it would require updating both the Play Store and F-Droid after each release.
##

**Comment by geekgonecrazy** [comment]
@BackIsBachus do you have any info on submitting to F-Droid and if there are any api's we could use to automate this as part of our build process?  The easier it is for us to automate, the more likely it is that we will include it :smile:

**Comment by ghost** [comment]
I'm nor very knowledgeable about how works F-Droid but from what I read it seems that you have to submit your app before it is accepted into the catalogue. You can do that by posting it [here](https://f-droid.org/forums/forum/submission-queue/) or if you can and want to speed up the process directly follow the instruction [here](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests). I think the last link can help you automate the update of the app on F-Droid.

I'm not really sure how to do this with app built with Cordova though (I'll try to find more info on that in the next few day).

**Comment by xenithorb** [comment]
+1 

Very much would like to see this please. Or on Aptoide. I don't use Google services, except GCM through microG GmsCore (floss gcm connector)

**Comment by wohali** [comment]
@geekgonecrazy Here's the walkthrough of [how to add a new app to F-Droid](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md). Here are their [requirements for an app to be accepted](https://f-droid.org/wiki/page/Inclusion_How-To). As previously mentioned you meet the Licensing requirements, and I don't think you use any closed-source binary blobs that they would reject.

Note, you won't be building the apk for them, rather they want to know how to build the apk from your repo. You'll be writing a build recipe for their system to build your app on their infrastructure. Be sure to include pointers to your issue tracker (here on GH) and any donations link to help funnel in those tasty donations! :smile_cat: 

I tried working out how to build the apk from your repo myself but I'm afraid your documentation on apk generation is a bit...sparse, and I'm not very fluent with Cordova.

If there is something I can do to help this along, let me know. I'd be willing to toss $20 or so your way if that would help :)

**Comment by geekgonecrazy** [comment]
@wohali thanks for the info!  I didn't realize F-Droid worked this way.  Reminds me a bit of Gentoo and other Linux distros :)

**Comment by herbsmn** [comment]
I see that you added a "help wanted" tag. Can you make a list of tasks that need accomplished in order for feature to be added so that we can help you out?

**Comment by geekgonecrazy** [comment]
@herbsmn from my understanding the big piece we don't have that we need to be listed... We need an F-DROID build script to compile the app.

**Comment by herbsmn** [comment]
@geekgonecrazy 

"The F-Droid server does not directly publish an APK online, instead the F-Droid server needs a buildable source to build an APK from. This way the server guarantees that the resulting APK accurately represents the source code without any hidden anti-features." https://f-droid.org/wiki/page/Inclusion_How-To

From what I understand, F-Droid needs your buildable source, instead of the other way around.

I suggest that one of the Rocket Chat Cordova developers create an initial submission here: https://f-droid.org/forums/forum/submission-queue/

After that, you can follow these steps to speed the process up a bit: https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md

**Comment by valessiobrito** [comment]
+1

**Comment by herbsmn** [comment]
hello?

**Comment by geekgonecrazy** [comment]
@herbsmn we haven't had the extra time to look into doing this currently.  We do post apk's with every release.  So we make it possible to get by with out Google Play. 

Thanks for your continued patience :smile:

**Comment by herbsmn** [comment]
thanks for the response @geekgonecrazy. i started this thread on the forums: https://f-droid.org/forums/topic/rocket-chat-cordova/

**Comment by amiryal** [comment]
Others already mentioned [fdroiddata/CONTRIBUTING.md](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md). I would just like to add that following it would not only speed the process up a bit, but in my experience is a **sure way** of getting it in **as fast as possible**.

**Comment by geekgonecrazy** [comment]
What do users that download through F-Droid do for notifications?

**Comment by xenithorb** [comment]
I use F-droid exclusively, it notifies you when there are new packages available in their repository. It checks their main repo by default at an interval specified from within the app. F-Droid app do not update automatically, yet, due to certain system permission limitations, but they do provide a notification for when there is an updated package.

I assume challenges are similar to building for fedora in that you have to follow their very specific build process which may not jive totally with prebuilt libraries.

**Comment by geekgonecrazy** [comment]
Poor wording on my part.  😄 

I meant like getting Push Notifications for the app.  I assume many F-Droid users are not going to make use of Google Play or Google Play Services?

But yes, there will for sure be those challenges with this as well

**Comment by xenithorb** [comment]
Understood, on that front GCM is either not used or in my case, since I also use Signal where GCM is required, there is a FLOSS microG drop-in replacement for google services framework and friends. 

https://microg.org

It's also a possibility that certain people will prefer to download certain apps through F-droid than other due to the nature of their open build system and trusting that process more than google play's black box. 

Edit: meaning that they'll have normal google apps and will just perfer to download the app through F-droid

**Comment by amiryal** [comment]
Not being a mobile developer, my previous comment was written before I realised what Cordova is. My searching the net brought this project up: [turtl/fdroid](https://github.com/turtl/fdroid). This led me to the section in [turtl/mobile/Makefile](https://github.com/turtl/mobile/blob/0a28ba51b6b61ae25ee9a683c8d4deebc318b63c/Makefile):

```
#fdroid: build-android
fdroid:
    rsync \
        -avz \
        --delete \
        --delete-excluded \
        --checksum \
        --exclude='build/' \
        --exclude='android/build/' \
        --exclude='.gradle/' \
        platforms/android/ ../fdroid/app

release-fdroid: fdroid
cd ../fdroid && ./scripts/release $(MOBILE_VERSION)
```

Where `../fdroid` is where [turtl/fdroid](https://github.com/turtl/fdroid) is cloned.

If something similar can be done in the Rocket.Chat.Cordova release process, then the resulting automatically generated project may be submitted to F-Droid. I couldn’t find `com.lyonbros.turtl` on [fdroid/fdroiddata](https://gitlab.com/fdroid/fdroiddata), though.

**Comment by amiryal** [comment]
Slightly off-topic: I’m new to Rocket.Chat, so wasn’t expecting any notifications yet. I installed the Android app from the [releases page](https://github.com/RocketChat/Rocket.Chat.Cordova/releases) – does that use GCM?

Also, I’m using a self-hosted Rocket.Chat server – does _that_ use GCM for pushing notifications?

**Comment by amiryal** [comment]
I believe that, in order to get accepted, the dependency on proprietary GCM will have to be removed in the project that gets submitted to fdroiddata.

**Comment by xenithorb** [comment]
@amiryal 

> Also, I’m using a self-hosted Rocket.Chat server – does that use GCM for pushing notifications?

Yes and no. 

The way it works by default if you use any of the published apps (instead of building your own) is that your server sends a notification to the push gateway @ https://rocket.chat, which then in turn sends it to GCM and therefore your app. This is because the distributed app has a hard-coded GCM id that points to the rocket.chat push gateway as indicated above.

The only way to achieve true privacy [from the perspective of not sending data to rocket.chat, google is a whole other can of worms] is to:
1. Build the app and change the GCM id yourself
   1. Distribute the app to your users
   2. Set the required information in Administration -> Certificates and Keys 

I had mentioned somewhere else earlier (can't find it) about possibly having the Cordova app acquire GCM id and keys from the server (since this is possible), in which case it would alleviate the strain on Rocket.Chat's gateway, enhance user privacy, and also be aligned with the install instructions that ask you to go acquire GCM info from google and fill it out. 

The reality is that `GCM API key` and `GCM Project Number` are totally useless and unused if `Enable Gateway: true` is set and also useless until you build and distribute your own app. 

Unfortunately that idea was shot down because they couldn't also achieve the same thing with APN. (Which I honestly didn't see a relation, if it works better for one why suffer because you can't do it for the other?)

**Comment by xenithorb** [comment]
All proprietary software need be removed, yes.

**Comment by herbsmn** [comment]
This issue came up with Signal. Someone wrote a fork that removed GCM push notifications are placed them with rudimentary WebSocket-ONLY support. https://github.com/JavaJens/TextSecure

**Comment by xenithorb** [comment]
Right, but since that's not well maintained and doesn't work very well (and its forks and sister repos are harassed and legally threatened by Moxie himself) what most people do is use the repo @ http://eutopia.cz which also serves the websocket-only build but also the "LibreSignal build" that somehow still uses GCM.

It's a sad situation where google has cornered the market so deeply when it comes to push messaging on android that there's literally no alternative, especially when their operating system is completely hostile to anything that does something simple like poll a server at a long interval. They've done exactly what they needed to do to make sure everyone except apple users has to use GCM, that's for sure.

I'm not sure what the answer is here.

**Comment by geekgonecrazy** [comment]
> Unfortunately that idea was shot down because they couldn't also achieve the same thing with APN. (Which I honestly didn't see a relation, if it works better for one why suffer because you can't do it for the other?)

I think its still an option on the table.

We're looking at: 
- Letting Android pull GCM info from server.  But since server can have multiple servers... have to make sure app can register with multiple project ids.
- e2e encrypting the notifications, so that no data is ever seen by the gateway.  (In the interm you can disable sending of content in the push notification)
-  [ownpush](https://ownpush.com/) - We've messed around with this alternative, and have talked to the creators.  We just haven't had time to implement.

**Comment by alexgleason** [comment]
Hi all,

@ccwalker22 and I created an F-Droid repo that contains RocketChat. Feel free to use it in the interim while we wait for a more permanent solution.

> https://f-droid.candlewaster.co/

**Comment by herbsmn** [comment]
Hey @inputmice, how do you do notifcations in Conversations without GCM? These guys are interested in doing the same thing, I think.

**Comment by herbsmn** [comment]
Does this way of doing notifications make sense for Rocket Chat Cordova? https://github.com/siacs/Conversations/blob/082c06a486fe4cdb8870680a33836f40d570d1fd/src/main/java/eu/siacs/conversations/services/NotificationService.java

**Comment by mddvul22** [comment]
@geekgonecrazy earlier in this thread, you mention that Rocket Chat posts the apk with each release.  Where are those apks available for download?  I see https://github.com/RocketChat/Rocket.Chat.Cordova/releases but that doesn't seem to be current anymore.  Looks like the latest release is 2.5.0 but that page shows 2.4.0.

**Comment by geekgonecrazy** [comment]
It appears when a release was released to play store a version wasn't tagged here.

@RocketChat/core can who ever tagged a release push the tag here?  I can upload the apk, just not sure what commit should be tagged.

**Comment by marmistrz** [comment]
@herbsmn
XMPP does an idle TCP on port 5222, so does Conversations, AFAIK.

On my phone (CM13.0/OnePlus 3) it works perfectly. But I have friends whose Android knows better what they don't need to communicate and kills the connection. But Conversations has an option to keep a persistent notification to prevent the system from killing the connection. Workaround for stupid Android design decisions, but works.

You can see this article: https://gultsch.de/xmpp_2016.html

**Comment by schaengel** [comment]
Any update on this issue, by the way there was no cordova release since aug 2016. So is this issue valid here or in the android app issue thread?

**Comment by Stemby** [comment]
https://github.com/RocketChat/Rocket.Chat.Android/issues/26 seems to be the current thread.

**Comment by martinszy** [comment]
1) The app is currently on f-droid, so I think the issue should be closed.

2) The app is not updating. At least in my phone is stuck in 3.2.0, but the f-droid catalog is aware of 3.4.1 as you can see here: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/chat.rocket.android.yml

What can be done?

**Comment by mddvul22** [comment]
This page still shows the latest version available in Fdroid as being 3.2.0:

https://f-droid.org/en/packages/chat.rocket.android/

**Comment by geekgonecrazy** [comment]
Going to close this.  All issues related to that listing should go on https://github.com/rocketchat/rocket.chat.android

**Comment by alexanderadam** [comment]
Just for clarification: the Kotlin version has already the open F-Droid issues [#2250](https://github.com/RocketChat/Rocket.Chat.Android/issues/2250), [#2339](https://github.com/RocketChat/Rocket.Chat.Android/issues/2339) and [#2179](https://github.com/RocketChat/Rocket.Chat.Android/issues/2179).
