### ISSUE TITLE
question: push notifications in cordova with plugin? 

### ISSUE THREAD

**Issue by maxlinux2000** [RocketChat/Rocket.Chat.Cordova#11]
Rocket.chat.cordova don't support push notifications... this occur because it's impossible or there is a way using this plugin below?
https://github.com/phonegap/phonegap-plugin-push

regards
MaX

**Comment by geekgonecrazy** [comment]
Its for sure possible.  With the current meteor package here we are limited because it handles all of the registration id stuff on the client side.  So we need an end point or something that from the client we can send the users registration id from the push notification service to the rocket.chat instance. So that when it tells GCM about the notification it knows which user / device to deliver to.

**Comment by rodrigok** [comment]
Push notifications works in the old app.

The current app (in Beta right now) supports Push Notification too.

**Comment by geekgonecrazy** [comment]
@rodrigok Regarding the new app, I haven't seen this working.  Tried with the demo and direct messaged my self from a new account with no luck.

**Comment by graywolf336** [comment]
You installed it from the Play Store right? As push notifications worked
fine for me today

**Comment by geekgonecrazy** [comment]
Yup play store in the testing group.

**Comment by rodrigok** [comment]
@geekgonecrazy I'm doing a lot of modifications in the app, so probably the push for the old app is broke and for the new app isn't stable yet.

**Comment by geekgonecrazy** [comment]
@rodrigok sounds good. I'll un-install / re-install see if that changes anything.
