### ISSUE TITLE
Please install ImageMagick issue

### ISSUE THREAD

**Issue by Artgit** [RocketChat/Rocket.Chat.Cordova#113]
I'm trying to execute following command:

`cordova prepare`

and got following issue:

```
New assets, compiling resources...
Error: Please install ImageMagick.
```

I have installed ImageMagick on my Windows 10 machine http://www.imagemagick.org/script/binary-releases.php#windows and added it to PATH variable.

What am I doing wrong and how to correctly  install ImageMagick ?
##

**Comment by geekgonecrazy** [comment]
I've never been able to successfully do it on windows.  

`ticons` is the package that's using imagemagick.  Might be worth checking their repo out.

**Comment by aison45** [comment]
install whit all options select

**Comment by vectorez** [comment]
@Artgit install whit all options select

**Comment by leolara** [comment]
I am having the same issue in Mac, how did you solve it?

**Comment by leolara** [comment]
I solved it running `brew install imagemagick`

The error message is confusing, because you do not know if it means to install a cordova plugin, a npm package or in the build system.

**Comment by jlebras** [comment]
I've been able to successfully build (and obviously prepare) rocket chat on Windows 10.

The problem here is that the version 7 of ImageMagick  does not provide executables like convert, identify, etc...
They become subcommands of the magick command (i.e magick identify...).

To my understanding, when using `cordova prepare`, some hook is called to generate icons with the help of the `ticons` node module which uses the `gm` module to access ImageMagick command lines.
The `gm` module does not find the required command lines and then fails saying that ImageMagick is missing.

To solve this I searched for an older version of the ImageMagick binary, (no time for compiling...) which I found [there ](http://www.imagemagick.org/download/binaries) (ImageMagick-6.9.5-9-Q8-x64-dll.exe).
Make sure you add it to your path and that should work.

**Comment by laggedHero** [comment]
The important point here is what @jlebras found out: the legacy commands (`convert` and etc).

The windows dll installer have an option to support legacy commands, you just need to select it.

@Artgit Did you got it up and running already?

PS.: I'll add to the readme more information about ImageMagick
