### ISSUE TITLE
Speed issues on startup and load

### ISSUE THREAD

**Issue by bkkilaru** [RocketChat/Rocket.Chat.Cordova#51]
Our team has been enjoying using the RocketChat mobile apps, but we encounter two major issues on a regular basis as active users:
1. When starting the app, we often get stuck on the blue screen and just get frozen there. This happens unpredictably, but consistently across users. I'm sure it's because of the hybrid app needing to load the page, but is there any fix for this?
2. Especially on Android, there is a very long delay/lag to open new channels. Sometimes this can extend to 30 sec to a 1 min of load time just waiting for the channel to display. Any fix for this?

Thanks!

**Comment by Burstaholic** [comment]
What device are you using? I have no performance issues on my 2013 Moto X or my new Nexus 5x, but I hear complaints of slow performance from others with older devices - it would be very useful to get an idea of what level of hardware has issues.

**Comment by mrplow** [comment]
It takes around 13 seconds from launching the Android app to the main chat screen for my nexus 5

**Comment by Burstaholic** [comment]
Hmm; my Nexus 5x on Marshmallow takes about 10 seconds from a cold start - I think slow initial startup may be just part of the deal with a Cordova app.

I'm more curious about problems after startup, like taking ~60s to open a new channel - that's not expected, to me anyway. 

Assuming the Rocket guys are cool with it, my latest PR changes the Crosswalk WebView configuration to use the latest version, which corresponds to Chrome 45 instead of the current Chrome 43 - that may help performance, but it's not guaranteed.

**Comment by rodrigok** [comment]
We added more visual feedbacks, the startup time is slow because the app needs to download informations about rooms, subscriptions, users, etc, our demo server have many rooms, so the startup should be more slow.

Please, try the Rocket.Chat server version 0.25.0 that will be released today.
